services:
  - type: web
    name: finance-ai-backend
    env: python
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URI
        fromService:
          type: pserv
          name: mongodb
          property: connectionString
      - key: DATABASE_NAME
        value: finance_db
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: GEMINI_API_KEY
        sync: false # Set this in Render dashboard

  - type: pserv
    name: mongodb
    env: mongodb
    ipAllowList: [] # Only accessible by other services in same project
    databaseName: finance_db

  - type: web
    name: finance-ai-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://finance-ai-backend.onrender.com
